package examen;

import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jaz
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
       this.getContentPane().setBackground(Color.CYAN);
       this.setTitle("Evaluación");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtCurp = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtWeb = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblCurp = new javax.swing.JLabel();
        lblWeb = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        btnVerificar = new javax.swing.JButton();
        lblVerificar = new javax.swing.JLabel();
        lblVerificarC = new javax.swing.JLabel();
        lblVemail = new javax.swing.JLabel();
        lblVWeb = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtCurp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCurpKeyTyped(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNombre.setText("Nombre");

        lblCurp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCurp.setText("Curp");

        lblWeb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblWeb.setText("Web");

        lblEmail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblEmail.setText("Email");

        btnVerificar.setBackground(new java.awt.Color(204, 102, 255));
        btnVerificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVerificar.setText("Verificar");
        btnVerificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 102, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Limpiar");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 102, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Salir");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCurp, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail)
                    .addComponent(lblWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCurp)
                            .addComponent(txtEmail)
                            .addComponent(txtWeb, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVerificar)
                            .addComponent(lblVerificarC)
                            .addComponent(lblVemail)
                            .addComponent(lblVWeb))
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre)
                    .addComponent(lblVerificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCurp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblVerificarC))
                    .addComponent(lblCurp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail)
                    .addComponent(lblVemail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWeb)
                    .addComponent(lblVWeb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerificar)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
         char validar=evt.getKeyChar();
         if(Character.isDigit(validar)){
             getToolkit().beep();
             evt.consume();
             this.lblVerificar.setText("Mal");
         }
         else{
             this.lblVerificar.setText("Bien");
         }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
          String cadena;
        cadena = txtCurp.getText();//Obtener texto ingresado en la caja de texto y guardarlo en una variable
        int largo = cadena.length();//Obtener longitud de la cadena que se ingreso en la caja de texto
        if (largo!=18) {//si el largo de la cadena no es de 18 manda un mensaje de error
            
           this.lblVerificarC.setText("Mal");

        } else {//si el largo de la cadena si es de 18 entonces ejecuta este codigo 

            //partimos nuestra cadena en varias subcadenas para evaluar cada una de ellas
            String pt1 = cadena.substring(0, 4);//parte 1 Nombres
            String pt2 = cadena.substring(4, 10);//parte 2 fecha nac
            String pt3 = cadena.substring(10, 11);//parte 3 sexo (H o M)
            String pt4 = cadena.substring(11, 13);//parte 4 entidad federativa (2 caraceteres)
            String pt5 = cadena.substring(13, 16);//parte 5 primer consonante de primer apellido, primer consonante de segundo apellido, primer consonante de nombre 
            String pt6 = cadena.substring(16, 18);//parte 6 2 digitos al azar 

          
            //si la primera parte tiene letras entonces se sigue al siguiente if, si no manda un mensaje de error
            if (pt1.matches("[A-Z]+")) {
                //si la segunda parte tiene numeros (por la fecha de nacimiento) entonces vamos bien y se sigue al siguiente if, si no manda un mensaje de error
                if (pt2.matches("[0-9]+")) {
                    //la tercera parte tiene que ser H o M por el sexo, si no es eso manda un mensaje de error
                    if (pt3.equals("M") || pt3.equals("H")) {
                        //la cuarta parte tiene que tener la clave de la entidad, si no es eso manda un mensaje de error    
                        if (pt4.equals("AS") || pt4.equals("BC") || pt4.equals("BS") || pt4.equals("CC") || pt4.equals("CS") || pt4.equals("CH") || pt4.equals("CL") || pt4.equals("CM") || pt4.equals("DF") || pt4.equals("DG") || pt4.equals("GT") || pt4.equals("GR") || pt4.equals("HG") || pt4.equals("JC") || pt4.equals("MC") || pt4.equals("MN") || pt4.equals("MS") || pt4.equals("NT") || pt4.equals("NL") || pt4.equals("OC") || pt4.equals("PL") || pt4.equals("QT") || pt4.equals("QR") || pt4.equals("SP") || pt4.equals("SL") || pt4.equals("SR") || pt4.equals("TC") || pt4.equals("TL") || pt4.equals("TS") || pt4.equals("VZ") || pt4.equals("YN") || pt4.equals("ZS")) {
                            if (pt5.matches("[A-Z]+")) {
                                //la quinta parte tiene que tener numeros, si no es eso manda un mensaje de error 
                                if (pt6.matches("[0-9]+")) {
                                    //si todo esta bien manda un mensaje de exito
                                    String nombre="Bien";
                                    this.lblVerificarC.setText(nombre);
                                } else {
                                     String mal="Mal";
                                    this.lblVerificarC.setText(mal);
                                }
                            } else {
                                String mal="Mal";
                                    this.lblVerificarC.setText(mal);
                            }
                        } else {
                             String mal="Mal";
                                    this.lblVerificarC.setText(mal);
                        }
                    } else {
                         String mal="Mal";
                                    this.lblVerificarC.setText(mal);
                    }
                } else {
                   String mal="Mal";
                                    this.lblVerificarC.setText(mal);
                }
            } else {
                 String mal="Mal";
                                    this.lblVerificarC.setText(mal);
                                   

            }
        }
       String [] cadenaSeparada;
   String cadenaSinSeparar=this.txtNombre.getText();
   cadenaSeparada=cadenaSinSeparar.split(" ");
    for (int i=0; i< cadenaSeparada.length; i++){
       
        System.out.println("Posicion "+ i+" es: "+ cadenaSeparada[i]);
    String menor=cadenaSeparada[0];
            
    if  (menor.length()<3){
           this.lblVerificar.setText("Mal");
                       
          }
    else{
        this.lblVerificar.setText("Bien");
    }
               
    }
    Pattern pattern = Pattern
                .compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        
        String email = this.txtEmail.getText();
 
        Matcher mather = pattern.matcher(email);
 
        if (mather.find() == true) {
            this.lblVemail.setText("Bien");
        } else {
           this.lblVemail.setText("Mal");
          
          

        }
      
        Pattern pat = Pattern
                .compile("^((((https?|ftps?|gopher|telnet|nntp)://)|(mailto:|news:))" +
                    "(%[0-9A-Fa-f]{2}|[-()_.!~*';/?:@&=+$, A-Za-z0-9])+)" + "([).!';/?:, ][[:blank:]])?$");
        
        String web = this.txtWeb.getText();
 
        Matcher mat = pat.matcher(web);
 
        if (mat.find() == true) {
            this.lblVWeb.setText("Bien");
        } else {
           this.lblVWeb.setText("Mal");
          
          
        }
        
        
        
        
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void txtCurpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCurpKeyTyped
       
    }//GEN-LAST:event_txtCurpKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     this.txtNombre.setText("");
     this.txtCurp.setText("");
     this.txtEmail.setText("");
     this.txtWeb.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel lblCurp;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblVWeb;
    private javax.swing.JLabel lblVemail;
    private javax.swing.JLabel lblVerificar;
    private javax.swing.JLabel lblVerificarC;
    private javax.swing.JLabel lblWeb;
    private javax.swing.JTextField txtCurp;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtWeb;
    // End of variables declaration//GEN-END:variables
}
